const PROCESS_GET_CART = 'PROCESS_GET_CART';
const PROCESS_GET_ADDRESS = 'PROCESS_GET_ADDRESS';
const PROCESS_GET_O2O = 'PROCESS_GET_O2O';


export default {
	PROCESS_GET_CART,
	PROCESS_GET_ADDRESS,
	PROCESS_GET_O2O
};