const CP_ADD_COUPON = 'CP_ADD_COUPON';
const CP_ADDED_COUPON = 'CP_ADDED_COUPON';
const CP_DELETE_COUPON = 'CP_DELETE_COUPON';
const CP_DELETED_COUPON = 'CP_DELETED_COUPON';
const CP_INVALID_COUPON = 'CP_INVALID_COUPON';
const CP_RESET_COUPON = 'CP_RESET_COUPON';


export default {
	CP_DELETE_COUPON,
	CP_ADD_COUPON,
	CP_ADDED_COUPON,
	CP_DELETED_COUPON,
	CP_INVALID_COUPON,
	CP_RESET_COUPON
};