const CP_ADD_COUPON = 'CP_ADD_COUPON';
const CP_ADDED_COUPON = 'CP_ADDED_COUPON';
const CP_DELETE_COUPON = 'CP_DELETE_COUPON';
const CP_DELETED_COUPON = 'CP_DELETED_COUPON';


export default {
	CP_DELETE_COUPON,
	CP_ADD_COUPON,
	CP_ADDED_COUPON,
	CP_DELETED_COUPON
};