const USER_REQUEST_PROFILE = 'USER_REQUEST_PROFILE';
const USER_RECEIVED_PROFILE = 'USER_RECEIVED_PROFILE';
const USER_FAILED_RESPONSE = 'USER_FAILED_RESPONSE';
const USER_GTM_PROFILE = 'USER_GTM_PROFILE';

export default {
	USER_REQUEST_PROFILE,
	USER_RECEIVED_PROFILE,
	USER_FAILED_RESPONSE,
	USER_GTM_PROFILE,
};