const PAY_LIST_PAYMENT_METHOD = 'PAY_LIST_PAYMENT_METHOD';
const PAY_LATEST_PAYMENT_METHOD = 'PAY_LATEST_PAYMENT_METHOD';
const PAY = 'PAY';


export default {
	PAY_LIST_PAYMENT_METHOD,
	PAY_LATEST_PAYMENT_METHOD,
	PAY
};