const PAY_LIST_PAYMENT_METHOD = 'PAY_LIST_PAYMENT_METHOD';
const PAY_LATEST_PAYMENT_METHOD = 'PAY_LATEST_PAYMENT_METHOD';
const PAY_PAYMENT_METHOD_CHANGED = 'PAY_PAYMENT_METHOD_CHANGED';
const PAY_PAYMENT_OPTION_CHANGED = 'PAY_PAYMENT_OPTION_CHANGED';
const PAY_NEW_CREDIT_CARD = 'PAY_NEW_CREDIT_CARD';
const PAY_CREDIT_CARD_SELECTED = 'PAY_CREDIT_CARD_SELECTED';
const PAY_CREDIT_CARD_DESELECT = 'PAY_CREDIT_CARD_DESELECT';
const PAY_CREDIT_CARD_ADD = 'PAY_CREDIT_CARD_ADD';
const PAY_CREDIT_CARD_BANK_ADD = 'PAY_CREDIT_CARD_BANK_ADD';
const PAY_CHANGE_BANK = 'PAY_CHANGE_BANK';
const PAY_UPDATED = 'PAY_UPDATED';
const PAY_APPLY_BIN = 'PAY_APPLY_BIN';
const PAY_VT_MODAL_BOX_TOGGLE = 'PAY_VT_MODAL_BOX_TOGGLE';
const PAY_ECASH_MODAL_BOX_TOGGLE = 'PAY_ECASH_MODAL_BOX_TOGGLE';
const PAY_CHANGE_OVO_NUMBER = 'PAY_CHANGE_OVO_NUMBER';
const PAY_PAYMENT_ERROR = 'PAY_PAYMENT_ERROR';
const PAY_ERROR = 'PAY_ERROR';
const PAY = 'PAY';

const paymentGroupName = {
	BANK_TRANSFER: 'bank_transfer',
	CREDIT_CARD: 'credit_card',
	INSTALLMENT: 'installment',
	CONVENIENCE_STORE: 'convenience_store',
	E_MONEY: 'e_money',
	INTERNET_BANKING: 'internet_banking'
};

const paymentMethodName = {
	VIRTUAL_ACCOUNT: 'virtual_account',
	BANK_TRANSFER: 'bank_transfer',
	COMMERCE_VERITRANS: 'commerce_veritrans',
	COMMERCE_VERITRANS_INSTALLMENT: 'commerce_veritrans_installment',
	POS_PAY: 'pos_pay'
};


export default {
	PAY_UPDATED,
	PAY_LIST_PAYMENT_METHOD,
	PAY_LATEST_PAYMENT_METHOD,
	PAY_PAYMENT_METHOD_CHANGED,
	PAY_PAYMENT_OPTION_CHANGED,
	PAY_NEW_CREDIT_CARD,
	PAY_CREDIT_CARD_SELECTED,
	PAY_CREDIT_CARD_DESELECT,
	PAY_CREDIT_CARD_BANK_ADD,
	PAY_CREDIT_CARD_ADD,
	PAY_CHANGE_BANK,
	PAY_VT_MODAL_BOX_TOGGLE,
	PAY_ECASH_MODAL_BOX_TOGGLE,
	PAY_CHANGE_OVO_NUMBER,
	PAY_PAYMENT_ERROR,
	PAY_ERROR,
	PAY,
	PAY_APPLY_BIN,
	paymentGroupName,
	paymentMethodName
};