const CRT_GET_CART = 'CRT_GET_CART';
const CRT_UPDATE_QTY = 'CRT_UPDATE_QTY';
const CRT_DELETE_CART = 'CRT_DELETE_CART';
const CRT_GO_SEND_ELIGIBLE = 'CRT_GO_SEND_ELIGIBLE';
const CRT_PLACE_ORDER = 'CRT_PLACE_ORDER';


export default {
	CRT_GET_CART,
	CRT_UPDATE_QTY,
	CRT_DELETE_CART,
	CRT_GO_SEND_ELIGIBLE,
	CRT_PLACE_ORDER
};