const ADDR_GET_ADDRESS = 'ADDR_GET_ADDRESS';
const ADDR_SAVE_ADDRESS = 'ADDR_SAVE_ADDRESS';
const ADDR_DROP_SHIPPER = 'ADDR_DROP_SHIPPER';
const ADDR_O2O_LIST = 'ADDR_O2O_LIST';
const ADDR_O2O_PROVINCE = 'ADDR_O2O_PROVINCE';
const ADDR_FAILED = 'ADDR_FAILED';

export default {
	ADDR_GET_ADDRESS,
	ADDR_SAVE_ADDRESS,
	ADDR_DROP_SHIPPER,
	ADDR_O2O_LIST,
	ADDR_O2O_PROVINCE,
	ADDR_FAILED
};