const TRACKING_REQUEST = 'TRACKING_REQUEST';
const TRACKING_SUCCESS = 'TRACKING_SUCCESS';
const TRACKING_FAILURE = 'TRACKING_FAILURE';


export default {
	TRACKING_REQUEST,
	TRACKING_SUCCESS,
	TRACKING_FAILURE
};