export const GET_API = 'GET_API';
export const GET_API_SUCCESS = 'GET_API_SUCCESS';
export const GET_API_FAILURE = 'GET_API_FAILURE';

export const POST_API = 'POST_API';
export const POST_API_SUCCESS = 'POST_API_SUCCESS';
export const POST_API_FAILURE = 'POST_API_SUCCESS';

export const DELETE_API = 'DELETE_API';
export const DELETE_API_SUCCESS = 'DELETE_API_SUCCESS';
export const DELETE_API_FAILURE = 'DELETE_API_FAILURE';